### ISSUE TITLE
 Create cloud foundry application in blue mix

### ISSUE THREAD

**Issue by vinayak26061990** [NYU-DEVOPS-INDIA/PROMOTIONS#4]
**As a** Promotion Scheme Deployer 
**I need** to create a Cloud Foundry Application in Bluemix  
**So that** eases creation and maintenance of applications and helps both developers and operators alike. 

**Assumptions:** 
* The cloud is deployed to handle a small application. 

**Acceptance Criteria:**
  1) When new promotions are added, Then cloud is able to scale well.
  2) When new users access the API, Then cloud is able to handle the traffic efficiently

**Comment by anujbora** [comment]
\o/
