### ISSUE TITLE
Test LIST all promotions

### ISSUE THREAD

**Issue by yangyangiscoding** [NYU-DEVOPS-INDIA/PROMOTIONS#41]
**As a** Promotion Scheme Tester
**I need** to test "list all promotion"
**So that** it benefits the customer as he/she can always get the list of all promotions

**Assumptions:**

- There is no limitation on listing all the promotion exists

**Acceptance Criteria:**

- If the Promotion exists it returns the list of all Promotions and their information
- If the Promotion does not exist then returns a proper error message and HTTP 404 return code.

**Comment by vinayak26061990** [comment]
Yangyang- your coverage testing doesn't cover this return code HTTP_404_NOT_FOUND
I will suggest to create a bug corresponding to this issue and fix it.

**Comment by vinayak26061990** [comment]
The coverage testing doesn't cover this return code HTTP_404_NOT_FOUND, so you have to  incorporate this test case, line number 62-64 in server_promotion.py
