### ISSUE TITLE
Test List All Inactive Promotions

### ISSUE THREAD

**Issue by wenhaolu93** [NYU-DEVOPS-INDIA/PROMOTIONS#49]
As a Promotion Scheme Tester
I need to test "list all inactive promotion"
So that it benefits the customer as he/she can always get the list of all inactive promotions

Assumptions:

The attribute status is a string and is either "Active" or "Inactive"
Acceptance Criteria:

If the Promotion with status "Inactive" exists it returns the list of all inactive Promotions and their information
If the Promotion with status "Inactive" does not exist then returns a proper error message and HTTP 404 return code.

**Comment by vinayak26061990** [comment]
There is no code merged into the master for testing the listing inactive promotions, so create the separate branch for this issue and get the latest code from master  if you have not, and after developing and testing the code create a pull request between the master and the issue branch  
Also make sure to cover both the return codes HTTP_200_OK and HTTP_404_NOT_FOUND
