### ISSUE TITLE
Incorporate redis database in Promotion Server code

### ISSUE THREAD

**Issue by vinayak26061990** [NYU-DEVOPS-INDIA/PROMOTIONS#52]
**As a** Promotion Scheme member
**I need** to change the promotion server code
**So that** it can incorporate Redis database

**Assumptions:** 
* Vagrant File already has Redis in it

**Acceptance Criteria:**
* Given the vagrant is up and server is running , all the promotion scheme data needs to be maintained in Redis DB instead of being maintained in memory for the session.

**Comment by cs4511** [comment]
@vinayak26061990 add the promotion folder as well. You forgot to add it.
